use_frameworks!
platform :ios, '9.3'

target 'uPortSDK_Example' do
  pod 'uPortSDK', :path => '../'
  pod 'BigInt'
  pod 'CryptoSwift'
  pod 'Alamofire', '~> 4.7'
  
  target 'uPortSDK_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
