#!/usr/bin/env sh

if ! command -v carthaged > /dev/null; then
  printf 'Carthage is not installed.\n'
  printf 'See https://github.com/Carthage/Carthage#quick-start for install instructions.\n'
  exit 1
fi

carthage update --platform iOS --no-use-binaries --cache-builds
